### ISSUE TITLE
Allow Retailers to add Paymend and Shipping info in their profile and use it as default when adding products

### ISSUE THREAD

**Issue by jakobkolb** [fdo-labs/nachbarschaftsmarktplatz#2]
I think, everything that makes it easier for shops to add their inventory is a big plus. And I think this could help, as it reduces the number of interactions needed.

**Comment by hesslau** [comment]
when creating your first article you can store it as a template and load settings such as payment and shipping info when creating another article
![Fairmondo](https://user-images.githubusercontent.com/2887499/77834853-25900180-7148-11ea-8871-481533640df9.png)
![Fairmondo (1)](https://user-images.githubusercontent.com/2887499/77834883-79024f80-7148-11ea-9f30-a9b4156de105.png)

**Comment by jakobkolb** [comment]
Ok, that works too!
