### ISSUE TITLE
Link to existing online shops of stores

### ISSUE THREAD

**Issue by jakobkolb** [fdo-labs/nachbarschaftsmarktplatz#53]
When a store does not have any articles listed on the marketplace, the link in the sidebar of the map should point to the URL of their online shop.

**Comment by hesslau** [comment]
so far the we don't have a field for an external homepage. needs to be added before this can be implemented

**Comment by hesslau** [comment]
i implemented a external_website field. check staging to test this. you can add your website in the "Edit Profile" -> "Über mich" section

**Comment by jakobkolb** [comment]
Cool! As far, as I've figured, now the "shop" link on the map points to the website, when there are no articles, and it points to the marktplatz page, once the user puts up their first article. However, on staging, it does not point pack to the website, when all articles have been deleted. Can we fix this? as soon as that's done, I all for putting it  live! :partying_face:

**Comment by jakobkolb** [comment]
Ok, I see that that (delete articles, link on map points to website again) is actually, how its supposed to work. Maybe the `user.articles.count` isn't reset right after deleting articles?
